source 'https://rubygems.org'

ruby '<%= ruby_version %>', :engine => '<%= engine %>', :engine_version => '<%= engine_version %>'

gem 'nokogiri'
gem 'sinatra'
gem 'eventmachine'
gem 'bcrypt'
gem 'bson'

platform :ruby do
  gem 'mysql'
  gem 'pg'
  gem 'rmagick' unless `which convert` == ''
end

platform :jruby do
  gem 'jdbc-mysql'
  gem 'jdbc-postgres'
end
